### ISSUE TITLE
支付时报错：生产：错误代码 ILLEGAL_PARTNER_EXTERFACE ； 测试：错误代码 ILLEGAL_PARTNER

### ISSUE THREAD

**Issue by digitalliuzg** [odoo-cn/payment#10]
操作系统环境：windows2008 R2      应用系统环境：GreenOdoo-8-win32
官网下载模块：技术名称：payment_alipay 许可：Affero GPL-3 最新版本：8.0.1.0
Alipay配置：
环境：生产：错误代码 ILLEGAL_PARTNER_EXTERFACE ；
      测试：错误代码 ILLEGAL_PARTNER
过程方法：手动；
PID:已配
KEY：已配
Email：已配（与支付宝账号一致）
Interface Type：Securied Transaction

**Comment by jeffery9** [comment]
查询了下 支付宝的 报错信息 https://cshall.alipay.com/support/help_detail.htm?help_id=397107
解释是

```
含义：没有权限访问该服务

有以下的几种原因：
1、没有签约这个接口的合同。
2、签约了相应的接口合同，但没有生效。
3、签约了相应的接口合同，但由于违规违法等原因被审核部门强制关闭。

出现这种情况最常见的原因是：
接口用错。如，签约的是担保交易的接口合同，商户网站上使用的却是双功能-担保/即时；签约的是担保交易的接口合同，商户网站上使用的却是即时到帐。
```
