### ISSUE TITLE
支付宝模块报错

### ISSUE THREAD

**Issue by mxx123** [odoo-cn/payment#7]
500: Internal Server Error
"service" while evaluating
"tx_values['service']"

QWeb
错误信息

Could not evaluate expression "tx_values['service']"
这些错误可能在展示模板的时候发生 payment_alipay.alipay_acquirer_button 和评估一下表达式 tx_values['service']

Traceback（最后几行）

  File "/opt/odoo/sources/odoo/openerp/tools/safe_eval.py", line 314, in safe_eval
    return eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
QWebException: "service" while evaluating
"tx_values['service']"

**Comment by jeffery9** [comment]
这是因为必填的字段 interface 没有选择

**Comment by leangjia** [comment]
把interface勾选上去，任意一个即可。
