### ISSUE TITLE
安装后，付款时的错误

### ISSUE THREAD

**Issue by alanljj** [odoo-cn/payment#9]
安装后，付款时的错误：

 500: Internal Server Error Error Error message: 
"service" while evaluating"tx_values['service']" 

QWeb Error message: 
Could not evaluate expression "tx_values['service']" 

The error occured while rendering the template payment_alipay.alipay_acquirer_button and evaluating the following expression: tx_values['service']

**Comment by jeffery9** [comment]
你没有设置支付宝的接口类型

**Comment by alanljj** [comment]
谢谢回复，我还在等支付宝审批，回头试一下结果

**Comment by jeffery9** [comment]
fixed in 9dac43145fab33432918541bfabf57395f1ece14

**Comment by alanljj** [comment]
git pull更新到你的修复版本后，支付时的错误变为：

500: Internal Server Error
Error

Error message:

External ID not found in the system: website.

如果需要详细的，我可以把Traceback贴出来。

**Comment by yangziyuan** [comment]
题主搞定了吗
